### ISSUE TITLE
trojan-go脚本在安装0.7.x版本的核心后会无法连接 

### ISSUE THREAD

**Issue by akirayoo** [phlinhng/v2ray-tcp-tls-web#22]
0.7版本开始的配置和旧版本配置文件有区别 会导致无法使用   而脚本默认是获取最新版核心的,,但脚本使用的确是旧版配置..有空的话修复下?

**Comment by phlinhng** [comment]
您好，我剛才重新試了一遍，發現復現不出來。（配置文件格式我從 0.6.0 開始就改了）在我的測試機上，用 v1.2.0 安裝 trojan-go 可以正常連接。
方便提供 ` systemctl status trojan-go` 和 `/usr/bin/trojan-go/trojan-go -config /etc/trojan-go/config.json` 的報錯信息給我參考嗎？

**Comment by wangfeng35** [comment]
systemctl status trojan-go的信息：
● trojan-go.service - Trojan-Go - An unidentifiable mechanism that helps you bypass GFW
   Loaded: loaded (/etc/systemd/system/trojan-go.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-06-28 12:17:23 UTC; 1s ago
     Docs: https://p4gefau1t.github.io/trojan-go/
  Process: 17592 ExecStart=/usr/bin/trojan-go -config /etc/trojan-go/config.json (code=exited, 
status=203/EXEC)
 Main PID: 17592 (code=exited, status=203/EXEC)
      CPU: 583us

Jun 28 12:17:23 instance-3 systemd[1]: Started Trojan-Go - An unidentifiable mechanism that helps you b
ypass GFW.
Jun 28 12:17:23 instance-3 systemd[1]: trojan-go.service: Main process exited, code=exited, sta
tus=203/EXEC
Jun 28 12:17:23 instance-3 systemd[1]: trojan-go.service: Unit entered failed state.
Jun 28 12:17:23 instance-3 systemd[1]: trojan-go.service: Failed with result 'exit-code'.

/usr/bin/trojan-go/trojan-go -config /etc/trojan-go/config.json 无错误 可以正常启动

**Comment by wangfeng35** [comment]
> systemctl status trojan-go的信息：
> ● trojan-go.service - Trojan-Go - An unidentifiable mechanism that helps you bypass GFW
> Loaded: loaded (/etc/systemd/system/trojan-go.service; enabled; vendor preset: enabled)
> Active: activating (auto-restart) (Result: exit-code) since Sun 2020-06-28 12:17:23 UTC; 1s ago
> Docs: https://p4gefau1t.github.io/trojan-go/
> Process: 17592 ExecStart=/usr/bin/trojan-go -config /etc/trojan-go/config.json (code=exited,
> status=203/EXEC)
> Main PID: 17592 (code=exited, status=203/EXEC)
> CPU: 583us
> 
> Jun 28 12:17:23 instance-3 systemd[1]: Started Trojan-Go - An unidentifiable mechanism that helps you b
> ypass GFW.
> Jun 28 12:17:23 instance-3 systemd[1]: trojan-go.service: Main process exited, code=exited, sta
> tus=203/EXEC
> Jun 28 12:17:23 instance-3 systemd[1]: trojan-go.service: Unit entered failed state.
> Jun 28 12:17:23 instance-3 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
> 
> /usr/bin/trojan-go/trojan-go -config /etc/trojan-go/config.json 无错误 可以正常启动

ExecStart=/usr/bin/trojan-go -config /etc/trojan-go/config.json
bin的路径不对，应该是/usr/bin/trojan-go/trojan-go

**Comment by phlinhng** [comment]
> ExecStart=/usr/bin/trojan-go -config /etc/trojan-go/config.json
> bin的路径不对，应该是/usr/bin/trojan-go/trojan-go

感謝 @wangfeng35 大佬協助。這次故障的原因是 trojan-go v0.7.x 的 `trojan-go.service` 內的路徑與以往版本不同造成的，和配置文件無關，現己修復。

**Comment by phlinhng** [comment]
己修復，己經用 v1.2.0 版本安裝 trojan-go 的用戶請升級腳本後運行"更新 trojan-go"即可解決。
